{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "5f38283f",
   "metadata": {},
   "outputs": [],
   "source": [
    "'''\n",
    "Develop a python program to demonstrate handling of following exceptions using try\n",
    "and except.\n",
    " NameError\n",
    " IndexError\n",
    " KeyError\n",
    " ZeroDivisionError\n",
    "'''\n",
    "\n",
    "def handle_exceptions():\n",
    "    # Handling NameError\n",
    "    try:\n",
    "        print(non_existent_variable)\n",
    "    except NameError as e:\n",
    "        print(f\"NameError caught: {e}\")\n",
    "'''\n",
    "Develop a python program to demonstrate handling of following exceptions using try\n",
    "and except.\n",
    " NameError\n",
    " IndexError\n",
    " KeyError\n",
    " ZeroDivisionError\n",
    "'''\n",
    "\n",
    "def handle_exceptions():\n",
    "    # Handling NameError\n",
    "    try:\n",
    "        print(non_existent_variable)\n",
    "    except NameError as e:\n",
    "        print(f\"NameError caught: {e}\")\n",
    "\n",
    "    # Handling IndexError\n",
    "    try:\n",
    "        my_list = [1, 2, 3]\n",
    "        print(my_list[5])\n",
    "    except IndexError as e:\n",
    "        print(f\"IndexError caught: {e}\")\n",
    "\n",
    "    # Handling KeyError\n",
    "    try:\n",
    "        my_dict = {'a': 1, 'b': 2}\n",
    "        print(my_dict['c'])\n",
    "    except KeyError as e:\n",
    "        print(f\"KeyError caught: {e}\")\n",
    "\n",
    "    # Handling ZeroDivisionError\n",
    "    try:\n",
    "        result = 10 / 0\n",
    "    except ZeroDivisionError as e:\n",
    "        print(f\"ZeroDivisionError caught: {e}\")\n",
    "\n",
    "# Call the function to see exception handling in action\n",
    "handle_exceptions()\n",
    "\n",
    "    # Handling IndexError\n",
    "    try:\n",
    "        my_list = [1, 2, 3]\n",
    "        print(my_list[5])\n",
    "    except IndexError as e:\n",
    "        print(f\"IndexError caught: {e}\")\n",
    "\n",
    "    # Handling KeyError\n",
    "    try:\n",
    "        my_dict = {'a': 1, 'b': 2}\n",
    "        print(my_dict['c'])\n",
    "    except KeyError as e:\n",
    "        print(f\"KeyError caught: {e}\")\n",
    "\n",
    "    # Handling ZeroDivisionError\n",
    "    try:\n",
    "        result = 10 / 0\n",
    "    except ZeroDivisionError as e:\n",
    "        print(f\"ZeroDivisionError caught: {e}\")\n",
    "\n",
    "# Call the function t'''\n",
    "Develop a python program to demonstrate handling of following exceptions using try\n",
    "and except.\n",
    " NameError\n",
    " IndexError\n",
    " KeyError\n",
    " ZeroDivisionError\n",
    "'''\n",
    "\n",
    "def handle_exceptions():\n",
    "    # Handling NameError\n",
    "    try:\n",
    "        print(non_existent_variable)\n",
    "    except NameError as e:\n",
    "        print(f\"NameError caught: {e}\")\n",
    "\n",
    "    # Handling IndexError\n",
    "    try:\n",
    "        my_list = [1, 2, 3]\n",
    "        print(my_list[5])\n",
    "    except IndexError as e:\n",
    "        print(f\"IndexError caught: {e}\")\n",
    "\n",
    "    # Handling KeyError\n",
    "    try:\n",
    "        my_dict = {'a': 1, 'b': 2}\n",
    "        print(my_dict['c'])\n",
    "    except KeyError as e:\n",
    "        print(f\"KeyError caught: {e}\")\n",
    "\n",
    "    # Handling ZeroDivisionError\n",
    "    try:\n",
    "        result = 10 / 0\n",
    "    except ZeroDivisionError as e:\n",
    "        print(f\"ZeroDivisionError caught: {e}\")\n",
    "\n",
    "# Call the function to see exception handling in action\n",
    "handle_exceptions()\n",
    "o see exception handling in action\n",
    "handle_exceptions()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "35b94c3a",
   "metadata": {},
   "outputs": [],
   "source": [
    "'''\n",
    "Develop a python program to demonstrate handling multiple exceptions using try,\n",
    "except, else and finally block statements.\n",
    "'''\n",
    "def handle_multiple_exceptions():\n",
    "    try:\n",
    "        # Code that may raise multiple exceptions\n",
    "        value = int(input(\"Enter a number: \"))  # May raise ValueError\n",
    "        result = 10 / value  # May raise ZeroDivisionError\n",
    "        my_list = [1, 2, 3]\n",
    "        print(my_list[value])  # May raise IndexError\n",
    "        my_dict = {'a': 1, 'b': 2}\n",
    "        print(my_dict[value])  # May raise KeyError if value is not 0 or 1\n",
    "\n",
    "    except ValueError as e:\n",
    "        print(f\"ValueError caught: {e}\")\n",
    "    \n",
    "    except ZeroDivisionError as e:\n",
    "        print(f\"ZeroDivisionError caught: {e}\")\n",
    "    \n",
    "    except IndexError as e:\n",
    "        print(f\"IndexError caught: {e}\")\n",
    "    \n",
    "    except KeyError as e:\n",
    "        print(f\"KeyError caught: {e}\")\n",
    "\n",
    "    else:\n",
    "        # This block will run if no exceptions were raised\n",
    "        print(\"All operations were successful!\")\n",
    "\n",
    "    finally:\n",
    "        # This block will always run\n",
    "        print(\"Execution completed, whether an exception was raised or not.\")\n",
    "\n",
    "# Call the function to demonstrate exception handling\n",
    "handle_multiple_exceptions()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "09bfe385",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Enter number: 12\n",
      "Enter number: 123\n",
      "Enter number: 12344\n",
      "Enter number: 12314\n",
      "Enter number: 13141\n",
      "Sum is 37934 and average is 7586.8\n"
     ]
    }
   ],
   "source": [
    "# Develop a python program to read 5 integer values from the keyboard. Display the\n",
    "# sum and average of these numbers. If the user enters any other value, then raise the\n",
    "# ValueError exception. Display appropriate messages.\n",
    "\n",
    "sum = 0\n",
    "try:\n",
    "    for i in range(5):\n",
    "        n = int(input(\"Enter number: \"))\n",
    "        sum += n;\n",
    "    print(f\"Sum is {sum} and average is {sum/5}\")\n",
    "except ValueError:\n",
    "    print(\"you didnt give integer value\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "5885ae8e",
   "metadata": {},
   "outputs": [],
   "source": [
    "'''\n",
    "Develop a python program to read the age of a person and display if he is eligible to\n",
    "vote or not. Raise the exception when the age range is less than 1 and greater than\n",
    "150.\n",
    "'''\n",
    "\n",
    "def check_voting_eligibility(age):\n",
    "    if age < 1 or age > 150:\n",
    "        raise ValueError(\"Age must be between 1 and 150\")\n",
    "    \n",
    "    if age >= 18:\n",
    "        print(\"You are eligible to vote!\")\n",
    "    else:\n",
    "        print(\"You are not eligible to vote yet.\")\n",
    "\n",
    "\n",
    "try:\n",
    "    age = int(input(\"Enter your age: \"))\n",
    "    check_voting_eligibility(age)\n",
    "except ValueError as e:\n",
    "    print(f\"Error: {e}. Please enter a valid age.\")\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "846c9899",
   "metadata": {},
   "outputs": [],
   "source": [
    "'''\n",
    "Write an interactive program to compute the square root of a number. The input\n",
    "values must be tested for validity. If it is negative, the user defined method MySqrt()\n",
    "should raise an exception.\n",
    "'''\n",
    "\n",
    "class NegativeNumberError(Exception):\n",
    "    def __init__(self, value):\n",
    "        self.value = value\n",
    "\n",
    "def MySqrt(num):\n",
    "    if num < 0:\n",
    "        raise NegativeNumberError(\"Square root of a negative number is not defined.\")\n",
    "    else:\n",
    "        return num ** 0.5\n",
    "\n",
    "\n",
    "while True:\n",
    "    try:\n",
    "        num = float(input(\"Enter a number to compute its square root (enter a negative number to exit): \"))\n",
    "            \n",
    "        if num < 0:\n",
    "            break\n",
    "            \n",
    "        result = MySqrt(num)\n",
    "        print(f\"The square root of {num} is {result:.4f}\")\n",
    "        \n",
    "    except ValueError:\n",
    "        print(\"Error: Please enter a valid number.\")\n",
    "    except NegativeNumberError as e:\n",
    "        print(f\"Error: {e}\")\n",
    "    except Exception as e:\n",
    "        print(f\"Error: {e}\")\n",
    "\n",
    "print(\"Exiting the program.\")\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "8dafc87b",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "d63976f5",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Current balance: 1000\n",
      "Deposit of 500 successful. New balance is 1500\n",
      "Current balance: 1500\n",
      "Withdrawal of 200 successful. New balance is 1300\n",
      "Current balance: 1300\n"
     ]
    },
    {
     "ename": "ValueError",
     "evalue": "Insufficient balance",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mValueError\u001b[0m                                Traceback (most recent call last)",
      "Input \u001b[0;32mIn [2]\u001b[0m, in \u001b[0;36m<cell line: 39>\u001b[0;34m()\u001b[0m\n\u001b[1;32m     37\u001b[0m account\u001b[38;5;241m.\u001b[39mwithdraw(\u001b[38;5;241m200\u001b[39m)\n\u001b[1;32m     38\u001b[0m account\u001b[38;5;241m.\u001b[39mcheck_balance()\n\u001b[0;32m---> 39\u001b[0m \u001b[43maccount\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mwithdraw\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;241;43m2000\u001b[39;49m\u001b[43m)\u001b[49m\n",
      "Input \u001b[0;32mIn [2]\u001b[0m, in \u001b[0;36mBank.withdraw\u001b[0;34m(self, amount)\u001b[0m\n\u001b[1;32m     22\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mValueError\u001b[39;00m(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mWithdrawal amount should be greater than zero\u001b[39m\u001b[38;5;124m\"\u001b[39m)\n\u001b[1;32m     23\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m amount \u001b[38;5;241m>\u001b[39m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mbalance:\n\u001b[0;32m---> 24\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mValueError\u001b[39;00m(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mInsufficient balance\u001b[39m\u001b[38;5;124m\"\u001b[39m)\n\u001b[1;32m     25\u001b[0m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mbalance \u001b[38;5;241m-\u001b[39m\u001b[38;5;241m=\u001b[39m amount\n\u001b[1;32m     26\u001b[0m \u001b[38;5;28mprint\u001b[39m(\u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mWithdrawal of \u001b[39m\u001b[38;5;132;01m{\u001b[39;00mamount\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m successful. New balance is \u001b[39m\u001b[38;5;132;01m{\u001b[39;00m\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mbalance\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m\"\u001b[39m)\n",
      "\u001b[0;31mValueError\u001b[0m: Insufficient balance"
     ]
    }
   ],
   "source": [
    "'''\n",
    "Write a program to simulate saving account processing in a bank using constructors.\n",
    "Create Deposit and Withdraw with other member function and Check for Validation\n",
    "while withdrawing the amount. Raise the appropriate exceptions when depositing and\n",
    "withdrawing an incorrect amount. Display appropriate messages.\n",
    "'''\n",
    "\n",
    "class Bank:\n",
    "    def __init__(self, account_number, account_holder_name, initial_balance=0):\n",
    "        self.account_number = account_number\n",
    "        self.account_holder_name = account_holder_name\n",
    "        self.balance = initial_balance\n",
    "\n",
    "    def deposit(self, amount):\n",
    "        if amount <= 0:\n",
    "            raise ValueError(\"Deposit amount should be greater than zero\")\n",
    "        self.balance += amount\n",
    "        print(f\"Deposit of {amount} successful. New balance is {self.balance}\")\n",
    "\n",
    "    def withdraw(self, amount):\n",
    "        if amount <= 0:\n",
    "            raise ValueError(\"Withdrawal amount should be greater than zero\")\n",
    "        if amount > self.balance:\n",
    "            raise ValueError(\"Insufficient balance\")\n",
    "        self.balance -= amount\n",
    "        print(f\"Withdrawal of {amount} successful. New balance is {self.balance}\")\n",
    "\n",
    "    def check_balance(self):\n",
    "        print(f\"Current balance: {self.balance}\")\n",
    "\n",
    "\n",
    "account = Bank(12345, \"John Doe\", 1000)\n",
    "    \n",
    "account.check_balance()\n",
    "account.deposit(500)\n",
    "account.check_balance()\n",
    "account.withdraw(200)\n",
    "account.check_balance()\n",
    "account.withdraw(2000) \n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c775407b",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.10"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
